language:
  - objective-c

env:
  matrix:
    # - PY_VERSION="2.7.5" PIP_VER="2.7"
    - VERSION=2.7.7
    - VERSION=3.3.5
    - VERSION=3.4.1

install:
  - set -vx  # echo commands
  - source travis_install.sh

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../travis_test.sh
